object Versions {
    const val kotlin = "1.5.20"
    const val gradle = "4.2.2"
    const val jUnit = "4.13.2"
    const val espressoCore = "3.4.0"
    const val constraintLayout = "2.0.4"
    const val coreKtx = "1.6.0"
    const val material = "1.4.0"
    const val junit = "1.1.3"
    const val appcompat = "1.4.0-alpha03"
    const val nav = "2.3.5"
    const val hilt = "2.35"
    const val coroutine = "1.5.0"
    const val protobufGradlePlugin = "0.8.16"
    const val protobufJava = "3.17.1"
    const val protoc = "3.17.2"
    const val protocJavalite = "3.0.0"
    const val jeromq = "0.5.2"
}

object Deps {
    const val gradle = "com.android.tools.build:gradle:${Versions.gradle}"
    const val kotlin = "org.jetbrains.kotlin:kotlin-stdlib:${Versions.kotlin}"
    const val appcompat = "androidx.appcompat:appcompat:${Versions.appcompat}"
    const val coreKtx = "androidx.core:core-ktx:${Versions.coreKtx}"
    const val material = "com.google.android.material:material:${Versions.material}"
    const val jUnit = "junit:junit:${Versions.jUnit}"
    const val junit = "androidx.test.ext:junit:${Versions.junit}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    const val espressoCore = "androidx.test.espresso:espresso-core:${Versions.espressoCore}"
    const val kotlinGradlePlugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlin}"
    const val navFragmentKtx = "androidx.navigation:navigation-fragment-ktx:${Versions.nav}"
    const val navUiKtx = "androidx.navigation:navigation-ui-ktx:${Versions.nav}"
    const val hiltAndroid = "com.google.dagger:hilt-android:${Versions.hilt}"
    const val hiltCompiler = "com.google.dagger:hilt-compiler:${Versions.hilt}"
    const val hiltAndroidGradlePlugin = "com.google.dagger:hilt-android-gradle-plugin:${Versions.hilt}"
    const val coroutineCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.coroutine}"
    const val coroutineAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.coroutine}"
    const val protobufGradlePlugin = "com.google.protobuf:protobuf-gradle-plugin:${Versions.protobufGradlePlugin}"
    const val protobufJava = "com.google.protobuf:protobuf-java:${Versions.protobufJava}"
    const val protoc = "com.google.protobuf:protoc:${Versions.protoc}"
    const val protocJavalite = "com.google.protobuf:protoc-gen-javalite:${Versions.protocJavalite}"
    const val jeromq = "org.zeromq:jeromq:${Versions.jeromq}"

}